version: '3.8'

volumes:
    vue-cli-node-volume:

services:
    client:
        image: vuecli:1
        build: 
            context: .
            dockerfile: client.dockerfile
        container_name: vuecli3
        ports:
            - "8080:8080"
        volumes:
            - vue-cli-node-volume:/app/client_app_2/node_modules
            - ./client_app_2:/app/client_app_2
        stdin_open: true
        tty: true
    server:
        image: openjdk:15
        container_name: openjdk15
        ports:
            - 65001:65001
        volumes:
            - ./server:/srv:cached
        stdin_open: true
        tty: true
    mysql:
        build: 
            context: .
            dockerfile: mysql.dockerfile
        container_name: mysql_container
        ports:
            - "3306:3306"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./mysql/db:/var/lib/mysql
